python3 ./PreProcess/generate_particle_and_inputfiles.py \
    --dimension 3 \
    --no_of_cell_in_x 25 \
    --buffery 5 \
    --periodic 0 \
    --np_per_cell_x 1 \
    --order_scheme 3 \
    --alpha_pic_flip 1.0 \
    --stress_update_scheme 1 \
    --CFL 0.1 \
    --output_tag 1D_Axial_Bar_Vibration_dim3_npcx1_ord3_flip1.0_sus1_CFL0.1_541aa9
