MPM_HOME ?= ../
AMREX_HOME ?= ${MPM_HOME}/Submodules/amrex

EBASE = ExaGOOP

DEBUG	= FALSE

DIM	= 3

COMP    = gnu

USE_TEMP = FALSE
DEFINES += -DUSE_TEMP=$(USE_TEMP)
DEFINES += -DTRUE=1 -DFALSE=0

USE_MPI   = TRUE 
USE_OMP   = FALSE
USE_CUDA  = FALSE
USE_HIP   = FALSE
USE_EB    = TRUE

TINY_PROFILE = FALSE
USE_PARTICLES = TRUE
BL_NO_FORT = TRUE

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include $(AMREX_HOME)/Src/Base/Make.package
include $(AMREX_HOME)/Src/Particle/Make.package
include $(AMREX_HOME)/Src/EB/Make.package
include $(AMREX_HOME)/Src/Boundary/Make.package
include $(AMREX_HOME)/Src/AmrCore/Make.package

include $(MPM_HOME)/Source/Make.package

INCLUDE_LOCATIONS += $(MPM_HOME)/Source
VPATH_LOCATIONS   += $(MPM_HOME)/Source

include $(AMREX_HOME)/Tools/GNUMake/Make.rules
